import { PdfDocumentBuilder } from './core/pdfDocumentBuilder'
import { formatDate, formatDateTime, formatEnum } from './core/pdfFormatters'
import type { Document } from '../../model/documents'

export interface PDFOptions {
  includeWatermark?: boolean
  includeFooter?: boolean
}

const DOCUMENT_TYPE_LABELS: Record<Document['type'], string> = {
  contract: 'Contract',
  invoice: 'Invoice',
  registration: 'Vehicle Registration',
  insurance: 'Insurance Policy',
  inspection: 'Technical Inspection Certificate',
  'tir-carnet': 'TIR Carnet',
  adr: 'ADR Certificate',
  'hazmat-permit': 'Hazmat Transport Permit',
  license: 'License',
  certificate: 'Certificate',
  other: 'Document'
}

const ENTITY_TYPE_LABELS: Record<Document['entityType'], string> = {
  vehicle: 'Vehicle',
  customer: 'Customer',
  supplier: 'Supplier',
  driver: 'Driver',
  company: 'Company',
  other: 'Other'
}

export async function generateDocumentPDF(document: Document, options: PDFOptions = {}): Promise<void> {
  const builder = await createDocumentBuilder(document, options)

  builder.sectionTitle('Document Information')
  builder.field('Document Name:', document.name)
  builder.field('Document Type:', getDocumentTypeLabel(document.type))
  builder.field('Document ID:', document.id)

  if (document.number) {
    builder.field('Document Number:', document.number)
  }

  builder.sectionTitle('Related Entity')
  builder.field('Related To:', getEntityTypeLabel(document.entityType))
  builder.field('Entity Name:', document.entityName)
  builder.field('Entity ID:', document.entityId)

  builder.sectionTitle('Important Dates')
  builder.field('Issue Date:', formatDateTime(document.issueDate))

  if (document.expiryDate) {
    builder.field('Expiry Date:', formatDateTime(document.expiryDate))
  }

  builder.field('Created:', formatDateTime(document.createdAt))
  builder.field('Last Updated:', formatDateTime(document.updatedAt))

  if (document.issuingAuthority) {
    builder.sectionTitle('Issuing Authority')
    builder.field('Authority:', document.issuingAuthority)
  }

  if (document.notes) {
    builder.sectionTitle('Notes')
    builder.paragraph(document.notes)
  }

  builder.sectionTitle('Document Content')
  builder.paragraph('This is a sample document generated by the Deliveroo TMS system.')
  builder.paragraph('This document contains all the relevant information as stored in the system.')

  const filename = `${document.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${document.id}.pdf`
  builder.save(filename)
}

export async function generateDocumentPDFBlob(document: Document, options: PDFOptions = {}): Promise<Blob> {
  const builder = await createDocumentBuilder(document, options)

  builder.sectionTitle('Document Information')
  builder.field('Document Name:', document.name)
  builder.field('Document Type:', getDocumentTypeLabel(document.type))
  builder.field('Document ID:', document.id)

  if (document.number) {
    builder.field('Document Number:', document.number)
  }

  builder.sectionTitle('Related Entity')
  builder.field('Related To:', getEntityTypeLabel(document.entityType))
  builder.field('Entity Name:', document.entityName)
  builder.field('Entity ID:', document.entityId)

  builder.sectionTitle('Important Dates')
  builder.field('Issue Date:', formatDateTime(document.issueDate))

  if (document.expiryDate) {
    builder.field('Expiry Date:', formatDateTime(document.expiryDate))
  }

  builder.field('Created:', formatDateTime(document.createdAt))
  builder.field('Last Updated:', formatDateTime(document.updatedAt))

  if (document.issuingAuthority) {
    builder.sectionTitle('Issuing Authority')
    builder.field('Authority:', document.issuingAuthority)
  }

  if (document.notes) {
    builder.sectionTitle('Notes')
    builder.paragraph(document.notes)
  }

  builder.sectionTitle('Document Content')
  builder.paragraph('This is a sample document generated by the Deliveroo TMS system.')
  builder.paragraph('This document contains all the relevant information as stored in the system.')

  return builder.toBlob()
}

function getDocumentTypeLabel(type: Document['type']): string {
  return DOCUMENT_TYPE_LABELS[type] ?? formatEnum(type)
}

function getEntityTypeLabel(type: Document['entityType']): string {
  return ENTITY_TYPE_LABELS[type] ?? formatEnum(type)
}

function createDocumentBuilder(document: Document, options: PDFOptions): Promise<PdfDocumentBuilder> {
  return PdfDocumentBuilder.create({
    title: getDocumentTypeLabel(document.type),
    includeWatermark: options.includeWatermark,
    includeFooter: options.includeFooter !== false,
    drawHeader(builder) {
      const doc = builder.internalDoc
      const pageWidth = builder.pageWidth

      const logoDataUrl = builder.logoDataUrl
      if (logoDataUrl) {
        doc.addImage(logoDataUrl, 'PNG', 20, 10, 40, 15)
      }

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.text('Transport Management System', pageWidth - 20 - 60, 15)
      doc.text('Deliveroo TMS Sp. z o.o.', pageWidth - 20 - 60, 22)

      doc.setLineWidth(0.5)
      doc.line(20, 30, pageWidth - 20, 30)

      doc.setFontSize(18)
      doc.setFont('helvetica', 'bold')
      doc.text(getDocumentTypeLabel(document.type), 20, 45)

      builder.currentY = 55
    },
    drawFooter(builder) {
      const doc = builder.internalDoc
      const pageWidth = builder.pageWidth
      const pageHeight = builder.pageHeight
      const footerY = pageHeight - 20

      doc.setLineWidth(0.5)
      doc.line(20, footerY - 5, pageWidth - 20, footerY - 5)

      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.text('Generated by Deliveroo TMS', 20, footerY)
      doc.text(`Generated on: ${formatDateTime(new Date())}`, pageWidth - 20 - 50, footerY)
      doc.text(`Page ${doc.getCurrentPageInfo().pageNumber} of ${doc.getNumberOfPages()}`, pageWidth / 2 - 10, footerY)
    }
  })
}
