services:
  wms-postgres:
    image: postgres:17-alpine
    container_name: wms-postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: deliveroo
    ports:
      - "5432:5432"
    volumes:
      - wms-postgres_data:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - deliveroo-network
    restart: unless-stopped

  wms-api-dev:
    container_name: wms-api-container
    profiles: [dev]
    build:
      context: ./wms-api
      dockerfile: Dockerfile
    command: python src/run.py
    environment:
      - PORT=3001
      - SERVICE_NAME=wms-api
      - POSTGRES_URL=postgresql+psycopg2://admin:strongpassword123@wms-postgres:5432/deliveroo
    ports:
      - "3001:3001"
    networks:
      deliveroo-network:
        aliases:
          - wms-api
    develop:
      watch:
        - action: sync
          path: ./wms-api/src
          target: /app/src
        - action: rebuild
          path: ./wms-api/requirements.txt

  wms-api-prod:
    container_name: wms-api-container
    profiles: [prod]
    build:
      context: ./wms-api
      dockerfile: Dockerfile
    command: >
      gunicorn --workers 4
               --bind 0.0.0.0:3001
               --pythonpath /app/src
               application:app
    environment:
      - PORT=3001
      - SERVICE_NAME=wms-api
      - POSTGRES_URL=postgresql+psycopg2://admin:strongpassword123@wms-postgres:5432/deliveroo
    ports:
      - "3001:3001"
    networks:
      deliveroo-network:
        aliases:
          - wms-api

  nginx:
    image: nginx:alpine
    container_name: wms-nginx-container
    profiles: [dev, prod]
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - deliveroo-network
    depends_on:
      wms-api-dev:
        condition: service_started
        required: false
      wms-api-prod:
        condition: service_started
        required: false
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - deliveroo-network
    depends_on:
      - wms-postgres
    restart: unless-stopped

networks:
  deliveroo-network:
    driver: bridge

volumes:
  wms-postgres_data:
  pgadmin_data:
